name: Request Unity Activation File

on:
  workflow_dispatch: {}   # Elle çalıştıracağız

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Request manual activation file (.alf)
        id: getalf
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 6000.0.58f2
          # Not: Bu action için customImage gerekmez/ desteklenmez.

      - name: Upload .alf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity-activation-file
          path: ${{ steps.getalf.outputs.filePath }}
